---
services:
  db:
    container_name: your_friend_db
    image: postgres:17.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: your_friend_backend
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DOCKER_ENV: "true"
    depends_on:
      - db

  frontend:
    container_name: your_friend_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: